# 原料成本 (13种原料，单位:元/MT)
costs: [2080, 1950, 1780, 1900, 2200, 2950, 5400, 680, 3300, 200, 550, 260, 2200]

# 营养矩阵 (13x7，7种营养素)
nutrition:
  #  DM    Ca    CP    P    NDF    ME     MP
  - [87.0, 0.09, 11.0, 0.33, 18.4, 12.12, 4.41]    # 大麦皮
  - [92.5, 0.24, 17.90, 1.04, 30.10, 10.83, 8.08]    # 小麦麸
  - [88.8, 0.07, 8.53, 0.23, 3.74, 13.04, 3.10]    # 玉米
  - [88.6, 0.13, 9.00, 0.36, 17.4, 12.23, 3.35]    # 高粱
  - [91.63, 0.27, 45.27, 0.54, 15.59, 12.43, 22.64]    # 大豆粕
  - [90.45, 0.23, 43.09, 0.93, 30.68, 10.76, 21.48]    # 棉籽粕
  - [88.0, 0.27, 47.8, 0.56, 15.50, 12.44, 23.99]    # 花生仁粕
  - [91.0, 0.49, 12.26, 0.07, 73.5, 6.02, 5.08]    # 羊草
  - [37.6, 0.0, 20.81, 0.0, 48.3, 8.81, 9.63]    # 苜蓿青贮
  - [92.4, 0.64, 4.25, 0.08, 76.2, 5.72, 0.96]    # 玉米秸秆
  - [90.5, 0.99, 5.22, 0.15, 77.4, 5.59, 1.34]    # 大豆秸秆
  - [31.03, 0.0, 6.6, 0.0, 74.7, 5.89, 2.07]    # 玉米秸秆青贮
#  - [90.34, 0.38, 6.45, 0.11, 66.29, 6.82, 1.99]    # 棉花秸秆
#  - [90.35, 0.18, 18.74, 0.56, 50.48, 7.69, 8.53]    # 向日葵仁粕
  - [99.40, 29.6, 0.0, 22.86, 0.0, 0.0, 0.0]    # 磷酸氢钙


# 营养指标上下界
nutrient_bounds:
  lower: [63, 0.85, 12.37, 0.48, 34.00, 7.62, 6.41]  # 下界
#  lower: [0, 0, 1, 0, 3, 3, 3]  # 下界
  upper: [98.1, 2.04, 31.1, 0.79, 46.0, 11.6, 10.8]  # 上界
#  upper: [100, 10.02, 140.84, 10.57, 44.00, 90.14, 70.69]  # 上界

# 原料用量限制 (13种原料上下界)
ingredient_bounds:
  lower: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]   # 下界
  upper: [1, 0.4, 0.4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]   # 上界

# 其他配置
settings:
  device: "cuda"          # 默认计算设备
  tol: 0.05              # 配方总和容差
