costs:
- 2080.0
- 1950.0
- 1780.0
- 1900.0
- 2200.0
- 2950.0
- 5400.0
- 680.0
- 3300.0
- 200.0
- 550.0
- 260.0
- 2200.0
ingredient_bounds:
  lower:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  upper:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
nutrient_bounds:
  lower:
  - 63.0
  - 0.85
  - 12.37
  - 0.48
  - 34.0
  - 7.62
  - 6.41
  upper:
  - 63.0
  - 0.85
  - 12.37
  - 0.48
  - 34.0
  - 7.62
  - 6.41
nutrition:
- - 87.0
  - 0.09
  - 11.0
  - 0.33
  - 18.4
  - 12.12
  - 4.41
- - 92.5
  - 0.24
  - 17.9
  - 1.04
  - 30.1
  - 10.83
  - 8.08
- - 88.8
  - 0.07
  - 8.53
  - 0.23
  - 3.74
  - 13.04
  - 3.1
- - 88.6
  - 0.13
  - 9.0
  - 0.36
  - 17.4
  - 12.23
  - 3.35
- - 91.63
  - 0.27
  - 45.27
  - 0.54
  - 15.59
  - 12.43
  - 22.64
- - 90.45
  - 0.23
  - 43.09
  - 0.93
  - 30.68
  - 10.76
  - 21.48
- - 88.0
  - 0.27
  - 47.8
  - 0.56
  - 15.5
  - 12.44
  - 23.99
- - 91.0
  - 0.49
  - 12.26
  - 0.07
  - 73.5
  - 6.02
  - 5.08
- - 37.6
  - 0.0
  - 20.81
  - 0.0
  - 48.3
  - 8.81
  - 9.63
- - 92.4
  - 0.64
  - 4.25
  - 0.08
  - 76.2
  - 5.72
  - 0.96
- - 90.5
  - 0.99
  - 5.22
  - 0.15
  - 77.4
  - 5.59
  - 1.34
- - 31.03
  - 0.0
  - 6.6
  - 0.0
  - 74.7
  - 5.89
  - 2.07
- - 99.4
  - 29.6
  - 0.0
  - 22.86
  - 0.0
  - 0.0
  - 0.0
settings:
  device: cuda
  tol: 0.05
